#!/bin/bash

D=`date "+%m%d%H%M%Y.%S"`

curl http://probabilistic-programming.org/research/index_bib.html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' > ./_bibliography/related.bib.new

if [ -a ./_bibliography/related.bib.new ]; then
  diff -u ./_bibliography/related.bib.new ./_bibliography/related.bib > /dev/null
  if [[ $? -eq 0 ]]; then
    echo "No new refs."
  else 
    echo "New refs."
    cp ./_bibliography/related.bib ./_bibliography/related.bib.$D;
    mv ./_bibliography/related.bib.new ./_bibliography/related.bib;
  fi;
fi;

jekyll build && rsync -avzc  --exclude '_site/_site*' _site/ fwood@login.robots.ox.ac.uk:~/WWW/anglican/
